export const CONFIG = {
  selectors: {
    kanbanContainer: 'kanbanContainer',
    langSelector: 'langSelector',

    boardSelector: 'boardSelector',
    addBoardBtn: 'addBoardBtn',
    renameBoardBtn: 'renameBoardBtn',
    deleteBoardBtn: 'deleteBoardBtn',

    createBoardModal: 'createBoardModal',
    createBoardOverlay: 'createBoardOverlay',
    createBoardForm: 'createBoardForm',
    newBoardName: 'newBoardName',
    newBoardTemplate: 'newBoardTemplate',
    cancelCreateBoard: 'cancelCreateBoard',

    renameBoardModal: 'renameBoardModal',
    renameBoardOverlay: 'renameBoardOverlay',
    renameBoardForm: 'renameBoardForm',
    renameBoardName: 'renameBoardName',
    cancelRenameBoard: 'cancelRenameBoard',

    deleteBoardModal: 'deleteBoardModal',
    deleteBoardOverlay: 'deleteBoardOverlay',
    deleteBoardName: 'deleteBoardName',
    deleteBoardMessage: 'deleteBoardMessage',
    confirmDeleteBoard: 'confirmDeleteBoard',
    cancelDeleteBoard: 'cancelDeleteBoard',

    searchInput: 'searchInput',
    filterLabel: 'filterLabel',
    filterPriority: 'filterPriority',
    clearFilters: 'clearFilters',
    filterBar: 'filterBar',
    importBtn: 'importBtn',
    exportBtn: 'exportBtn',
    importFileInput: 'importFileInput',

    addColumnModal: 'addColumnModal',
    modalOverlay: 'modalOverlay',
    addColumnForm: 'addColumnForm',
    columnTitleInput: 'columnTitleInput',
    addColumnBtn: 'addColumnBtn',
    cancelAddColumn: 'cancelAddColumn',

    cardDetailModal: 'cardDetailModal',
    cardDetailOverlay: 'cardDetailOverlay',
    cardDetailForm: 'cardDetailForm',
    cardTitleInput: 'cardTitleInput',
    cardDescriptionInput: 'cardDescriptionInput',
    cardDetailCloseBtn: 'cardDetailCloseBtn',
    cancelCardDetail: 'cancelCardDetail',
    cardStartDateInput: 'cardStartDateInput',
    cardDueDateInput: 'cardDueDateInput',
    cardEffortInput: 'cardEffortInput',
    cardCompletedInput: 'cardCompletedInput',
    cardPriorityInput: 'cardPriorityInput',
    labelsSelector: 'labelsSelector',

    cardLogList: 'cardLogList',
    newLogInput: 'newLogInput',
    addLogBtn: 'addLogBtn',

    manageLabelModal: 'manageLabelModal',
    manageLabelOverlay: 'manageLabelOverlay',
    manageLabelCloseBtn: 'manageLabelCloseBtn',
    manageLabelBtn: 'manageLabelBtn',
    labelsList: 'labelsList',
    newLabelName: 'newLabelName',
    newLabelColor: 'newLabelColor',
    addLabelBtn: 'addLabelBtn',
  },
  keys: {
    escape: 'Escape',
  },
  values: {
    debugRatio: 0.7,
    swapThreshold: 0.025,
  },
};
